/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: '📝 Introduction',
    },
    {
      type: 'doc',
      id: 'quickstart',
      label: '🚀 Quickstart',
    },
    {
      type: 'doc',
      id: 'routing',
      label: '🎨 Routing',
    },
    {
      type: 'doc',
      id: 'middleware',
      label: '💥 Middleware',
    },
    {
      type: 'doc',
      id: 'context',
      label: '🍻 Context',
    },
    {
      type: 'doc',
      id: 'validation',
      label: '📌 Validation',
    },
    {
      type: 'category',
      label: '🎉 Examples',
      collapsed: false,
      items: [
        'examples/contextual-data',
        'examples/cookie',
        'examples/routing_group',
        'examples/response_header',
        'examples/custom_not_found',
        'examples/success_and_fail',
      ],
    },
    {
      type: 'doc',
      id: 'cli',
      label: '🚧 CLI',
    },
    {
      type: 'doc',
      id: 'deployment',
      label: '🚧 Deployment',
    },
    {
      type: 'doc',
      id: 'faq',
      label: '🚧 FAQ',
    },

    // {
    //   type: 'category',
    //   label: 'Tutorial',
    //   items: ['tutorial-basics/create-a-document'],
    // },
  ],
  middlewareSidebar: [
    'middlewares/introduction',

    {
      type: 'category',
      label: 'Official middleware',
      collapsed: false,
      items: [
        'middlewares/requestid',
        'middlewares/compress',
        'middlewares/cors',
        'middlewares/static',
        'middlewares/pprof',
      ],
    },
    // {
    //   type: 'category',
    //   label: 'Community Middleware',
    //   items: ['middlewares/requestid'],
    // },
  ],
};

module.exports = sidebars;
